
GET http://localhost:8080/api/v1/status HTTP/1.1

###

GET http://localhost:8080/index.html HTTP/1.1

###

GET http://localhost:8080/global.css HTTP/1.1

###

GET http://localhost:8080/build/bundle.js HTTP/1.1

###

GET http://localhost:8080/projects/global.css HTTP/1.1

