@startuml Domain Entities
package toplevel {

  class Project {
    The Project.
    -- Required Fields --
    .. (1) ..
    +UUID id
    +ValueObject type
    +ValueObject shortcode
    +ValueObject name
    +MultiLanguageText description
    +Date startDate

    .. (1 - n) ..
    +Dataset[] datasets
    +MultiLanguageText[] keywords
    +TextOrAuthorityRef[] disciplines
    +TextOrAuthorityRef[] temporalCoverages
    +AuthorityRef[] spatialCoverages
    +LegalBody[] funders

    .. (1 - 2) ..
    +URL[] urls

    -- Optional Fields --
    .. (0 - 1) ..
    +DataManagementPlan dataManagementPlan
    +Date endDate
    +LegalBody contactPoint

    .. (0 - n) ..
    +ValueObject[] publications
    +Grant[] grants
    +MultiLanguageText[] alternativeNames
  }

  class Dataset {
    A Dataset belonging to the project.
    -- Required Fields --
    .. (1) ..
    +UUID id
    +ValueObject type
    +ValueObject title
    +ValueObject accessConditions
    +ValueObject howToCite
    +Status status

    .. (1 - n) ..
    +TextOrURL[] abstracts
    +TypesOfData[] typesOfData
    +URL[] licenses
    +MultiLanguageText[] languages
    +Attribution[] attributions

    -- Optional Fields --
    .. (0 - 1) ..
    +Date datePublished
    +Date dateCreated
    +Date dateModified
    +URL distribution

    .. (0 - n) ..
    +MultiLanguageText[] alternativeTitles
    +AuthorityRef[] sameAs
    +TextOrURL[] documentations
  }

  class DataManagementPlan {
    .. (1) ..
    +UUID id
    +ValueObject type

    .. (0 - 1) ..
    +boolean available
    +URL url

  }

  class Grant {
    A financial grant.
    -- Required Fields --
    .. (1 - n) ..
    +LegalBody[] funders

    -- Optional Fields --
    .. (0 - 1) ..
    +ValueObject number
    +MultiLanguageText name
    +URL url

  }

  interface LegalBody {
    Struct representing either a Person or an Organization.
    -- Required: OneOf --
    +Person person
    +Organization organization
  }

  class Person {
    A Person.
    -- Required --
    .. (1) ..
    +UUID id
    +ValueObject type

    .. (1 - n) ..
    +ValueObject[] jobTitles
    +ValueObject[] givenNames
    +ValueObject[] familyNames
    +Organization[] memberOf

    -- Optional --
    .. (0 - 1) ..
    +Address address

    .. (0 - 2) ..
    +ValueObject[] emails

    .. (0 - n) ..
    +AuthorityRef[] sameAs

  }

  class Organization {
    An Organization.
    -- Required --
    .. (1) ..
    +UUID id
    +ValueObject type
    + ValueObject name

    -- Optional --
    .. (0 - 1) ..
    +URL url
    +Address address
    +ValueObject email

    .. (0 - n) ..
    +MultiLanguageText[] alternativeNames

  }

  class Address {
    Struct containing a postal address.
    -- Required --
    .. (1) ..
    +ValueObject street
    +ValueObject postalCode
    +ValueObject locality
    +ValueObject country

    -- Optional --
    .. (0 - 1) ..
    +ValueObject additional

  }

  class Attribution {
    Struct holding information on how work on a dataset can be attributed to a person.
    -- Required Fields --
    .. (1) ..
    +Person person
    .. (1 - n) ..
    +ValueObject[] roles

  }
  

}

package utility {

  class TextOrAuthorityRef {
    Struct ensuring the object to be either a multi language text or an authority file reference.
    -- Required: OneOf --
    +AuthorityRef authorityRef
    +MultiLanguageText text
  }

  class TextOrURL {
    Struct ensuring the object to be either a multi language text or an aURL.
    -- Required: OneOf --
    +URL url
    +MultiLanguageText text
  }

  class AuthorityRef {
    Reference to an external autority file.
    -- Required Fields --
    +URL url
    +ValueObject authority
  }

  class MultiLanguageText {
    Struct holding text in multiple different languages.
    -- Required Fields --
    +Map[ValueObject,ValueObject] text
  }

  class ValueObject {
    Struct holding exactly one value.
  }

  class URL {
    ?
  }

  class Date {
    Struct holding an ISO-Date.
    -- Required Fields --
    .. (1) ..
    +ValueObject date
  }
  

  enum TypesOfData {
    XML
    Text
    Image
    Movie
    Audio
  }

  enum Status {
    In_planning
    Ongoing
    On_hold
    Finished
  }

}

package externals {
  class uuid::UUID {
    Unique ID.
  }
}


Project <..> Dataset
Project --> DataManagementPlan
Project --> Grant
Project --> LegalBody
Dataset --> Attribution
Attribution --> Person
Grant --> LegalBody
LegalBody --> Person
LegalBody --> Organization
Person --> Organization
Person --> Address
Organization --> Address
TextOrAuthorityRef --> MultiLanguageText
TextOrAuthorityRef --> AuthorityRef
TextOrURL --> URL
TextOrURL --> MultiLanguageText
AuthorityRef --> ValueObject
MultiLanguageText --> ValueObject

@enduml
