@startuml Domain Entities
package toplevel {

  class Project {
    The Project.
    -- Required Fields --
    .. (1) ..
    +ValueObject shortcode
    +ValueObject name
    +MultiLanguageText description
    +Date startDate

    .. (1 - n) ..
    +Dataset[] datasets
    +MultiLanguageText[] keywords
    +TextOrAuthorityRef[] discipline
    +TextOrAuthorityRef[] temporalCoverage
    +AuthorityRef[] spatialCoverage

    .. (1 - 2) ..
    +URL url
    ' TODO: do we want URL?

    -- Optional Fields --
    .. (0 - 1) ..
    +DataManagementPlan dataManagementPlan
    +Date endDate

    .. (0 - n) ..
    +ValueObject[] publication
    +Grant[] grant
    +MultiLanguageText[] alternateName
  }

  class Dataset {
    A Dataset belonging to the project.
    ' TODO
    -- Required Fields --
    .. (1) ..

    .. (1 - n) ..

    -- Optional Fields --
    .. (0 - 1) ..

    .. (0 - n) ..
  }

  class DataManagementPlan {
    .. (0 - 1) ..
    +boolean available
    +URL url
    ' TODO: do we want URL?
  }

  class Grant {
    A financial grant.
    -- Required Fields --
    .. (1 - n) ..
    +LegalBody funder

    -- Optional Fields --
    .. (0 - 1) ..
    +ValueObject number
    +MultiLanguageText name
    +URL url
    ' TODO: do we want URL?

  }

  class LegalBody {
    Struct representing either a Person or an Organization.
    -- Required: OneOf --
    +Person person
    +Organization organization
  }

  class Person {
    ' TODO
  }

  class Organization {
    ' TODO
  }

}

package utility {

  class TextOrAuthorityRef {
    ' TODO: find better name
    Struct ensuring the object to be either a multi language text or an authority file reference.
    -- Required: OneOf --
    +AuthorityRef authorityRef
    +MultiLanguageText text
  }

  class AuthorityRef {
    Reference to an external autority file.
    -- Required Fields --
    +ValueObject url
    +ValueObject authority
  }

  class MultiLanguageText {
    Struct holding text in multiple different languages.
    -- Required Fields --
    +Map[ValueObject,ValueObject] text
  }

  class ValueObject {
    Struct holding exactly one value.
  }

}


Project --> Dataset
Project --> DataManagementPlan
Project --> Grant
Project --> Person
Project --> Organization
Dataset --> Person
Dataset --> Organization
Grant --> LegalBody
LegalBody --> Person
LegalBody --> Organization
TextOrAuthorityRef --> MultiLanguageText
TextOrAuthorityRef --> AuthorityRef
AuthorityRef --> ValueObject
MultiLanguageText --> ValueObject

@enduml
