classDiagram
  Project "1" --> "1..*" Dataset
  Project "1" --> "0..1" DataManagementPlan

  class Project {
    +dataManagementPlan DataManagementPlan|nil
    +publication Text
    +name Text
    +description 
  }
  
  class Dataset {

  }

  class Person {

  }

  class Organization {

  }

  class Grant {

  }

  class DataManagementPlan {

  }

  class Text {
    %%+contents Map[string]string
  }
